[launcher]
author=Aarti Garg

[package]
id=agentic_ai_observability

[ui]
is_visible=1
label=Agentic AI Observability

[app]
build=1
description=AI-powered observability platform for monitoring and auto-remediating AI agent behavior
version=1.0.0
